export type NodeInfo = { name: string; skill: number; ports: number };
export const nodes: NodeInfo[] = [
    { name: "foodnstuff", skill: 1, ports: 0 },
    { name: "n00dles", skill: 1, ports: 0 },
    { name: "sigma-cosmetics", skill: 5, ports: 0 },
    { name: "joesguns", skill: 10, ports: 0 },
    { name: "nectar-net", skill: 20, ports: 0 },
    { name: "hong-fang-tea", skill: 30, ports: 0 },
    { name: "harakiri-sushi", skill: 40, ports: 0 },
    { name: "neo-net", skill: 50, ports: 1 },
    { name: "CSEC", skill: 51, ports: 1 },
    { name: "zer0", skill: 75, ports: 1 },
    { name: "max-hardware", skill: 80, ports: 1 },
    { name: "iron-gym", skill: 100, ports: 1 },
    { name: "phantasy", skill: 100, ports: 2 },
    { name: "silver-helix", skill: 150, ports: 2 },
    { name: "omega-net", skill: 202, ports: 2 },
    { name: "avmnite-02h", skill: 211, ports: 2 },
    { name: "crush-fitness", skill: 227, ports: 2 },
    { name: "johnson-ortho", skill: 264, ports: 2 },
    { name: "the-hub", skill: 292, ports: 2 },
    { name: "I.I.I.I", skill: 365, ports: 3 },
    { name: "computek", skill: 372, ports: 3 },
    { name: "rothman-uni", skill: 380, ports: 3 },
    { name: "catalyst", skill: 421, ports: 3 },
    { name: "netlink", skill: 424, ports: 3 },
    { name: "summit-uni", skill: 444, ports: 3 },
    { name: "rho-construction", skill: 510, ports: 3 },
    { name: "millenium-fitness", skill: 524, ports: 3 },
    { name: "aevum-police", skill: 434, ports: 4 },
    { name: ".", skill: 542, ports: 4 },
    { name: "run4theh111z", skill: 545, ports: 4 },
    { name: "alpha-ent", skill: 548, ports: 4 },
    { name: "syscore", skill: 590, ports: 4 },
    { name: "lexo-corp", skill: 691, ports: 4 },
    { name: "snap-fitness", skill: 751, ports: 4 },
    { name: "unitalife", skill: 785, ports: 4 },
    { name: "zb-def", skill: 785, ports: 4 },
    { name: "applied-energetics", skill: 793, ports: 4 },
    { name: "global-pharm", skill: 807, ports: 4 },
    { name: "univ-energy", skill: 828, ports: 4 },
    { name: "nova-med", skill: 849, ports: 4 },
    { name: "darkweb", skill: 1, ports: 5 },
    { name: "zb-institute", skill: 746, ports: 5 },
    { name: "solaris", skill: 793, ports: 5 },
    { name: "deltaone", skill: 807, ports: 5 },
    { name: "microdyne", skill: 816, ports: 5 },
    { name: "galactic-cyber", skill: 847, ports: 5 },
    { name: "zeus-med", skill: 850, ports: 5 },
    { name: "vitalife", skill: 851, ports: 5 },
    { name: "helios", skill: 854, ports: 5 },
    { name: "omnia", skill: 858, ports: 5 },
    { name: "aerocorp", skill: 862, ports: 5 },
    { name: "titan-labs", skill: 871, ports: 5 },
    { name: "icarus", skill: 872, ports: 5 },
    { name: "stormtech", skill: 880, ports: 5 },
    { name: "infocomm", skill: 881, ports: 5 },
    { name: "The-Cave", skill: 925, ports: 5 },
    { name: "taiyang-digital", skill: 927, ports: 5 },
    { name: "powerhouse-fitness", skill: 961, ports: 5 },
    { name: "defcomm", skill: 994, ports: 5 },
    { name: "fulcrumtech", skill: 1013, ports: 5 },
    { name: "omnitek", skill: 1022, ports: 5 },
    { name: "blade", skill: 1032, ports: 5 },
    { name: "b-and-a", skill: 1069, ports: 5 },
    { name: "ecorp", skill: 1155, ports: 5 },
    { name: "megacorp", skill: 1188, ports: 5 },
    { name: "kuai-gong", skill: 1192, ports: 5 },
    { name: "nwo", skill: 1197, ports: 5 },
    { name: "4sigma", skill: 1204, ports: 5 },
    { name: "clarkinc", skill: 1228, ports: 5 },
    { name: "fulcrumassets", skill: 1570, ports: 5 },
];

export const enum ServicePort {
    HarvestTimer = 1,
    HarvestTimerMessage = 2,
}
