export type NodeInfo = { name: string; skill: number; ports: number };
export const nodes: NodeInfo[] = [
    { name: "foodnstuff", skill: 1, ports: 0 },
    { name: "n00dles", skill: 1, ports: 0 },
    { name: "sigma-cosmetics", skill: 5, ports: 0 },
    { name: "joesguns", skill: 10, ports: 0 },
    { name: "nectar-net", skill: 20, ports: 0 },
    { name: "hong-fang-tea", skill: 30, ports: 0 },
    { name: "harakiri-sushi", skill: 40, ports: 0 },
    { name: "neo-net", skill: 50, ports: 1 },
    { name: "CSEC", skill: 59, ports: 1 },
    { name: "zer0", skill: 75, ports: 1 },
    { name: "max-hardware", skill: 80, ports: 1 },
    { name: "iron-gym", skill: 100, ports: 1 },
    { name: "phantasy", skill: 100, ports: 2 },
    { name: "silver-helix", skill: 150, ports: 2 },
    { name: "omega-net", skill: 197, ports: 2 },
    { name: "avmnite-02h", skill: 208, ports: 2 },
    { name: "johnson-ortho", skill: 259, ports: 2 },
    { name: "crush-fitness", skill: 271, ports: 2 },
    { name: "the-hub", skill: 292, ports: 2 },
    { name: "I.I.I.I", skill: 365, ports: 3 },
    { name: "computek", skill: 372, ports: 3 },
    { name: "rothman-uni", skill: 380, ports: 3 },
    { name: "netlink", skill: 424, ports: 3 },
    { name: "summit-uni", skill: 428, ports: 3 },
    { name: "catalyst", skill: 439, ports: 3 },
    { name: "rho-construction", skill: 489, ports: 3 },
    { name: "millenium-fitness", skill: 501, ports: 3 },
    { name: "aevum-police", skill: 416, ports: 4 },
    { name: "run4theh111z", skill: 506, ports: 4 },
    { name: ".", skill: 506, ports: 4 },
    { name: "alpha-ent", skill: 538, ports: 4 },
    { name: "syscore", skill: 598, ports: 4 },
    { name: "lexo-corp", skill: 668, ports: 4 },
    { name: "snap-fitness", skill: 736, ports: 4 },
    { name: "global-pharm", skill: 763, ports: 4 },
    { name: "unitalife", skill: 775, ports: 4 },
    { name: "applied-energetics", skill: 781, ports: 4 },
    { name: "zb-def", skill: 806, ports: 4 },
    { name: "univ-energy", skill: 835, ports: 4 },
    { name: "nova-med", skill: 832, ports: 4 },
    { name: "darkweb", skill: 1, ports: 5 },
    { name: "zb-institute", skill: 742, ports: 5 },
    { name: "solaris", skill: 757, ports: 5 },
    { name: "titan-labs", skill: 814, ports: 5 },
    { name: "vitalife", skill: 820, ports: 5 },
    { name: "galactic-cyber", skill: 825, ports: 5 },
    { name: "zeus-med", skill: 836, ports: 5 },
    { name: "helios", skill: 852, ports: 5 },
    { name: "icarus", skill: 856, ports: 5 },
    { name: "deltaone", skill: 871, ports: 5 },
    { name: "microdyne", skill: 874, ports: 5 },
    { name: "aerocorp", skill: 888, ports: 5 },
    { name: "infocomm", skill: 921, ports: 5 },
    { name: "omnia", skill: 943, ports: 5 },
    { name: "taiyang-digital", skill: 936, ports: 5 },
    { name: "The-Cave", skill: 925, ports: 5 },
    { name: "powerhouse-fitness", skill: 977, ports: 5 },
    { name: "defcomm", skill: 987, ports: 5 },
    { name: "fulcrumtech", skill: 994, ports: 5 },
    { name: "stormtech", skill: 1001, ports: 5 },
    { name: "b-and-a", skill: 1068, ports: 5 },
    { name: "nwo", skill: 1078, ports: 5 },
    { name: "omnitek", skill: 1094, ports: 5 },
    { name: "blade", skill: 1103, ports: 5 },
    { name: "clarkinc", skill: 1195, ports: 5 },
    { name: "4sigma", skill: 1235, ports: 5 },
    { name: "kuai-gong", skill: 1262, ports: 5 },
    { name: "megacorp", skill: 1296, ports: 5 },
    { name: "ecorp", skill: 1345, ports: 5 },
    { name: "fulcrumassets", skill: 1433, ports: 5 },
];

export const enum ServicePort {
    HarvestTimer = 1,
    HarvestTimerMessage = 2,
}
